# Ubuntu 14.04 Trusty support
sudo: required
dist: precise
language: cpp

addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake

compiler:
  - g++
  - clang++
  
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - cd ..
  - ./iron